// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-xrwwHQoP0yx2OfFjw6EHSQZQ-f1lJcc',
    appId: '1:323067637577:web:82818454188f94cded3498',
    messagingSenderId: '323067637577',
    projectId: 'smart-pantry-bd481',
    authDomain: 'smart-pantry-bd481.firebaseapp.com',
    storageBucket: 'smart-pantry-bd481.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKz7ScNkE0usCJrwnH6UM3bwFBHa2Ht7A',
    appId: '1:323067637577:android:5581ae81b26184aced3498',
    messagingSenderId: '323067637577',
    projectId: 'smart-pantry-bd481',
    storageBucket: 'smart-pantry-bd481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxx66O_RD-YPc5q_H67E2EofPn77xfMuk',
    appId: '1:323067637577:ios:e118f8a998765328ed3498',
    messagingSenderId: '323067637577',
    projectId: 'smart-pantry-bd481',
    storageBucket: 'smart-pantry-bd481.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxx66O_RD-YPc5q_H67E2EofPn77xfMuk',
    appId: '1:323067637577:ios:e118f8a998765328ed3498',
    messagingSenderId: '323067637577',
    projectId: 'smart-pantry-bd481',
    storageBucket: 'smart-pantry-bd481.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-xrwwHQoP0yx2OfFjw6EHSQZQ-f1lJcc',
    appId: '1:323067637577:web:54041213e87c875bed3498',
    messagingSenderId: '323067637577',
    projectId: 'smart-pantry-bd481',
    authDomain: 'smart-pantry-bd481.firebaseapp.com',
    storageBucket: 'smart-pantry-bd481.firebasestorage.app',
  );
}
